// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package c

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[IDENT-2]
	_ = x[INT-3]
	_ = x[FLOAT-4]
	_ = x[DOUBLE-5]
	_ = x[CHAR-6]
	_ = x[STRING-7]
	_ = x[CONSTINT-8]
	_ = x[IF-9]
	_ = x[ELSE-10]
	_ = x[FOR-11]
	_ = x[WHILE-12]
	_ = x[DO-13]
	_ = x[SWITCH-14]
	_ = x[CASE-15]
	_ = x[DEFAULT-16]
	_ = x[BREAK-17]
	_ = x[CONTINUE-18]
	_ = x[RETURN-19]
	_ = x[CONST-20]
	_ = x[STRUCT-21]
	_ = x[ENUM-22]
	_ = x[STATIC-23]
	_ = x[EXTERN-24]
	_ = x[INLINE-25]
	_ = x[TRUE-26]
	_ = x[FALSE-27]
	_ = x[NULL-28]
	_ = x[ASSIGN-29]
	_ = x[PLUS-30]
	_ = x[MINUS-31]
	_ = x[STAR-32]
	_ = x[SLASH-33]
	_ = x[PERCENT-34]
	_ = x[INCREMENT-35]
	_ = x[DECREMENT-36]
	_ = x[EQ-37]
	_ = x[NEQ-38]
	_ = x[LT-39]
	_ = x[GT-40]
	_ = x[LTE-41]
	_ = x[GTE-42]
	_ = x[AND-43]
	_ = x[OR-44]
	_ = x[NOT-45]
	_ = x[BIT_AND-46]
	_ = x[BIT_OR-47]
	_ = x[BIT_XOR-48]
	_ = x[BIT_NOT-49]
	_ = x[SHL-50]
	_ = x[SHR-51]
	_ = x[PLUSEQ-52]
	_ = x[MINUSEQ-53]
	_ = x[DIVEQ-54]
	_ = x[MULEQ-55]
	_ = x[LPAREN-56]
	_ = x[RPAREN-57]
	_ = x[LBRACE-58]
	_ = x[RBRACE-59]
	_ = x[LBRACKET-60]
	_ = x[RBRACKET-61]
	_ = x[COMMA-62]
	_ = x[SEMICOLON-63]
	_ = x[SPACE-64]
	_ = x[VOLATILE-65]
	_ = x[GOTO-66]
	_ = x[SHORT-67]
	_ = x[UNSIGNED-68]
	_ = x[SIGNED-69]
	_ = x[SIZEOF-70]
	_ = x[TYPEDEF-71]
	_ = x[UNION-72]
	_ = x[VOID-73]
}

const _TokenType_name = "ILLEGALEOFIDENTINTFLOATDOUBLECHARSTRINGCONSTINTIFELSEFORWHILEDOSWITCHCASEDEFAULTBREAKCONTINUERETURNCONSTSTRUCTENUMSTATICEXTERNINLINETRUEFALSENULLASSIGNPLUSMINUSSTARSLASHPERCENTINCREMENTDECREMENTEQNEQLTGTLTEGTEANDORNOTBIT_ANDBIT_ORBIT_XORBIT_NOTSHLSHRPLUSEQMINUSEQDIVEQMULEQLPARENRPARENLBRACERBRACELBRACKETRBRACKETCOMMASEMICOLONSPACEVOLATILEGOTOSHORTUNSIGNEDSIGNEDSIZEOFTYPEDEFUNIONVOID"

var _TokenType_index = [...]uint16{0, 7, 10, 15, 18, 23, 29, 33, 39, 47, 49, 53, 56, 61, 63, 69, 73, 80, 85, 93, 99, 104, 110, 114, 120, 126, 132, 136, 141, 145, 151, 155, 160, 164, 169, 176, 185, 194, 196, 199, 201, 203, 206, 209, 212, 214, 217, 224, 230, 237, 244, 247, 250, 256, 263, 268, 273, 279, 285, 291, 297, 305, 313, 318, 327, 332, 340, 344, 349, 357, 363, 369, 376, 381, 385}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
